services:
  db:
    image: postgres:16-alpine
    container_name: utang-db
    restart: always
    environment:
      # TODO: Set the Postgres Username
      POSTGRES_USER: kristian
      # TODO: Set the Postgres Password
      POSTGRES_PASSWORD: 605240
      # TODO: Set the default database name
      POSTGRES_DB: utang_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
